if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='vi'
fi
alias "rr"="rm -rf __pycache__"
alias "gs"="git status"
alias "ll"="ls -la"
alias "a"="source .venv/bin/activate"
alias "dc"="deactivate"
alias "lg"="lazygit"

export PATH="$PATH:$HOME/.local/scripts/:$HOME/go/bin/"
